import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { TemplateMapper } from './components/TemplateMapper';
import { FileUpload } from './components/FileUpload';

type ClothingType = 'shirt' | 'tshirt';

const App: React.FC = () => {
    const [clothingType, setClothingType] = useState<ClothingType>('shirt');
    const [generatedImage, setGeneratedImage] = useState<HTMLImageElement | null>(null);
    const [referenceImage, setReferenceImage] = useState<string | null>(null); // Base64 string for API
    const [referenceImagePreview, setReferenceImagePreview] = useState<string | null>(null); // Preview URL

    // The final template data URL generated by the mapper
    const [templateDataUrl, setTemplateDataUrl] = useState<string | null>(null);

    const [showGuides, setShowGuides] = useState<boolean>(true);
    const [scale, setScale] = useState<number>(0.25);

    // AI State
    const [prompt, setPrompt] = useState<string>("");
    const [isGenerating, setIsGenerating] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);

    const handleReferenceImageSelect = (img: HTMLImageElement) => {
        setReferenceImage(img.src.split(',')[1]); // Keep only base64 data
        setReferenceImagePreview(img.src);
        setError(null);
    };

    const clearReferenceImage = () => {
        setReferenceImage(null);
        setReferenceImagePreview(null);
    };

    const handleDownloadImage = (dataUrl: string | null, filename: string) => {
        if (dataUrl) {
            const link = document.createElement('a');
            link.download = filename;
            link.href = dataUrl;
            link.click();
        }
    };

    const handleGenerate = async () => {
        // If no prompt is provided but we have an image, we can still generate a variation
        if (!prompt.trim() && !referenceImage) {
            setError("텍스트 프롬프트를 입력하거나 레퍼런스 이미지를 업로드하세요.");
            return;
        }

        setIsGenerating(true);
        setError(null);
        setGeneratedImage(null);
        setTemplateDataUrl(null);

        try {
            const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_API_KEY });

            let systemPrompt = "";

            if (clothingType === 'shirt') {
                systemPrompt = `Generate a 2D texture map for a Roblox shirt. 
        Focus on the FRONT view of the shirt.
        Center: The chest/torso design.
        Sides: The sleeve texture.
        Style: "${prompt}"
        Requirements: Flat, 2D, no perspective, seamless pattern style. High contrast.`;
            } else {
                systemPrompt = `Generate a square graphic design logo/sticker.
        Subject: "${prompt}"
        Style: Vector art, sticker style, high quality, vibrant, isolated.
        Aspect Ratio: 1:1 Square.`;
            }

            // Construct parts array
            const parts: any[] = [{ text: systemPrompt }];

            // Add reference image if available
            if (referenceImage) {
                parts.push({
                    inlineData: {
                        mimeType: "image/png", // Assuming PNG/JPG from FileUpload
                        data: referenceImage
                    }
                });
                parts[0].text += " Use the attached image as a style reference.";
            }

            // Using 'gemini-2.5-flash-image' (Nano Banana) for broader access and speed
            // Note: This model does not support 'imageSize' in config.
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: {
                    parts: parts,
                },
                config: {
                    imageConfig: {
                        aspectRatio: "1:1",
                        // imageSize is NOT supported in gemini-2.5-flash-image
                    },
                },
            });

            // Find the image part in the response
            let base64Image = "";
            if (response.candidates && response.candidates[0].content.parts) {
                for (const part of response.candidates[0].content.parts) {
                    if (part.inlineData) {
                        base64Image = part.inlineData.data;
                        break;
                    }
                }
            }

            if (base64Image) {
                const img = new Image();
                img.onload = () => {
                    setGeneratedImage(img);
                };
                img.src = `data:image/png;base64,${base64Image}`;
            } else {
                throw new Error("이미지를 생성하지 못했습니다. (모델 응답 없음)");
            }

        } catch (err: any) {
            console.error("Generation error:", err);
            // Nice error message handling
            if (err.message?.includes('403')) {
                setError("권한 오류(403): API 키가 유효하지 않거나, 해당 모델에 접근할 수 없습니다.");
            } else {
                setError(err.message || "디자인 생성에 실패했습니다.");
            }
        } finally {
            setIsGenerating(false);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleGenerate();
        }
    };

    return (
        <div className="min-h-screen bg-gray-900 text-white font-sans selection:bg-roblox-blue selection:text-white">
            {/* Header */}
            <header className="border-b border-gray-800 bg-gray-900/95 sticky top-0 z-10 backdrop-blur-sm">
                <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-roblox-blue to-purple-600 rounded-lg flex items-center justify-center shadow-lg">
                            <span className="font-bold text-xl">R</span>
                        </div>
                        <h1 className="text-xl font-bold tracking-tight">Roblox <span className="text-roblox-blue">AI Designer</span></h1>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className="px-2 py-1 rounded bg-yellow-500/20 text-yellow-300 text-xs font-medium border border-yellow-500/30">Gemini 2.5 Flash</span>
                    </div>
                </div>
            </header>

            <main className="max-w-7xl mx-auto px-4 py-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

                    {/* Left Panel: Controls & Input */}
                    <div className="lg:col-span-5 space-y-6">

                        {/* Mode Selector - Big & Clear */}
                        <section className="bg-gray-800 rounded-2xl p-6 shadow-xl border border-gray-700">
                            <h2 className="text-lg font-semibold mb-4 text-gray-200">1. 의상 종류 선택</h2>
                            <div className="grid grid-cols-2 gap-4">
                                <button
                                    onClick={() => setClothingType('shirt')}
                                    className={`relative overflow-hidden p-4 rounded-xl border-2 transition-all duration-300 text-left group ${clothingType === 'shirt'
                                        ? 'border-roblox-blue bg-roblox-blue/10 shadow-[0_0_15px_rgba(0,162,255,0.3)]'
                                        : 'border-gray-700 bg-gray-800 hover:border-gray-600'
                                        }`}
                                >
                                    <div className={`absolute top-0 right-0 w-16 h-16 bg-gradient-to-bl from-roblox-blue to-transparent opacity-10 rounded-bl-full transition-opacity ${clothingType === 'shirt' ? 'opacity-20' : 'opacity-0'}`}></div>
                                    <div className="text-2xl mb-1">👔</div>
                                    <div className={`font-bold text-lg ${clothingType === 'shirt' ? 'text-roblox-blue' : 'text-gray-400'}`}>Classic Shirt</div>
                                    <div className="text-xs text-gray-500 mt-1">몸통과 팔을 감싸는<br />전신 의상 템플릿</div>
                                </button>

                                <button
                                    onClick={() => setClothingType('tshirt')}
                                    className={`relative overflow-hidden p-4 rounded-xl border-2 transition-all duration-300 text-left group ${clothingType === 'tshirt'
                                        ? 'border-roblox-green bg-roblox-green/10 shadow-[0_0_15px_rgba(0,176,111,0.3)]'
                                        : 'border-gray-700 bg-gray-800 hover:border-gray-600'
                                        }`}
                                >
                                    <div className={`absolute top-0 right-0 w-16 h-16 bg-gradient-to-bl from-roblox-green to-transparent opacity-10 rounded-bl-full transition-opacity ${clothingType === 'tshirt' ? 'opacity-20' : 'opacity-0'}`}></div>
                                    <div className="text-2xl mb-1">🖼️</div>
                                    <div className={`font-bold text-lg ${clothingType === 'tshirt' ? 'text-roblox-green' : 'text-gray-400'}`}>T-Shirt</div>
                                    <div className="text-xs text-gray-500 mt-1">가슴 앞면에 붙이는<br />그래픽 스티커/로고</div>
                                </button>
                            </div>
                        </section>

                        {/* AI Generation Section */}
                        <section className="bg-gray-800 rounded-2xl p-6 shadow-xl border border-gray-700 relative overflow-hidden">
                            <h2 className="text-lg font-semibold mb-4 flex items-center gap-2 relative z-10">
                                2. 디자인 생성
                            </h2>

                            <div className="space-y-4 relative z-10">
                                {/* Prompt Input */}
                                <div>
                                    <label className="block text-sm text-gray-400 mb-2">
                                        {clothingType === 'shirt'
                                            ? "원하는 셔츠의 재질, 패턴, 스타일을 설명하세요."
                                            : "티셔츠에 들어갈 로고나 그림을 설명하세요."}
                                    </label>
                                    <textarea
                                        value={prompt}
                                        onChange={(e) => setPrompt(e.target.value)}
                                        onKeyDown={handleKeyDown}
                                        placeholder={clothingType === 'shirt'
                                            ? "예: 검은색 가죽 자켓, 금색 지퍼 디테일, 펑크 스타일..."
                                            : "예: 귀여운 픽셀 고양이, 불타는 해골 로고, 네온 사인..."
                                        }
                                        className={`w-full bg-gray-900 border border-gray-600 rounded-xl p-3 text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:border-transparent transition-all resize-none h-28 ${clothingType === 'shirt' ? 'focus:ring-roblox-blue' : 'focus:ring-roblox-green'}`}
                                        disabled={isGenerating}
                                    />
                                </div>

                                {/* Reference Image Input */}
                                <div>
                                    <label className="block text-sm text-gray-400 mb-2">스타일 레퍼런스 (선택사항)</label>

                                    {!referenceImagePreview ? (
                                        <FileUpload onImageSelected={handleReferenceImageSelect} />
                                    ) : (
                                        <div className="relative group">
                                            <img
                                                src={referenceImagePreview}
                                                alt="Reference"
                                                className="w-full h-32 object-cover rounded-xl border border-gray-600 opacity-80"
                                            />
                                            <div className="absolute inset-0 flex items-center justify-center bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity rounded-xl">
                                                <button
                                                    onClick={clearReferenceImage}
                                                    className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-full text-sm font-bold"
                                                >
                                                    제거하기
                                                </button>
                                            </div>
                                            <div className="absolute top-2 right-2 bg-blue-600 text-xs px-2 py-1 rounded text-white shadow">
                                                참조 이미지 적용됨
                                            </div>
                                        </div>
                                    )}
                                </div>

                                {error && (
                                    <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-sm text-red-300">
                                        🚨 {error}
                                    </div>
                                )}

                                <button
                                    onClick={handleGenerate}
                                    disabled={isGenerating || (!prompt.trim() && !referenceImage)}
                                    className={`w-full py-4 rounded-lg font-bold text-lg shadow-lg flex items-center justify-center gap-2 transition-all ${isGenerating
                                        ? 'bg-gray-700 cursor-wait text-gray-400'
                                        : clothingType === 'shirt'
                                            ? 'bg-gradient-to-r from-roblox-blue to-blue-600 hover:brightness-110 active:scale-[0.98] text-white'
                                            : 'bg-gradient-to-r from-roblox-green to-emerald-600 hover:brightness-110 active:scale-[0.98] text-white'
                                        }`}
                                >
                                    {isGenerating ? (
                                        <>
                                            <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                            </svg>
                                            AI 생성 중...
                                        </>
                                    ) : (
                                        <>
                                            ✨ 디자인 생성하기
                                        </>
                                    )}
                                </button>
                            </div>
                        </section>

                        {/* Template Settings (Only for Shirts) */}
                        {clothingType === 'shirt' && (
                            <section className="bg-gray-800 rounded-2xl p-6 shadow-xl border border-gray-700">
                                <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                                    템플릿 미세조정
                                </h2>

                                <div className="space-y-4">
                                    <div className="flex items-center justify-between">
                                        <label className="text-gray-300 font-medium">가이드라인 표시</label>
                                        <button
                                            onClick={() => setShowGuides(!showGuides)}
                                            className={`w-12 h-6 rounded-full p-1 transition-colors duration-200 ease-in-out ${showGuides ? 'bg-roblox-blue' : 'bg-gray-600'}`}
                                        >
                                            <div className={`bg-white w-4 h-4 rounded-full shadow-md transform transition-transform duration-200 ${showGuides ? 'translate-x-6' : 'translate-x-0'}`}></div>
                                        </button>
                                    </div>

                                    <div>
                                        <div className="flex justify-between mb-1">
                                            <label className="text-gray-300 font-medium">패턴 크기 (Scale)</label>
                                            <span className="text-xs text-roblox-blue bg-roblox-blue/10 px-2 py-0.5 rounded">{scale.toFixed(2)}x</span>
                                        </div>
                                        <input
                                            type="range"
                                            min="0.1"
                                            max="2.0"
                                            step="0.05"
                                            value={scale}
                                            onChange={(e) => setScale(parseFloat(e.target.value))}
                                            className="w-full h-2 bg-gray-700 rounded-lg appearance-none cursor-pointer accent-roblox-blue"
                                        />
                                    </div>
                                </div>
                            </section>
                        )}
                    </div>

                    {/* Right Panel: Result */}
                    <div className="lg:col-span-7 flex flex-col gap-6">
                        <div className="bg-gray-800 rounded-2xl p-6 shadow-xl border border-gray-700 flex flex-col h-full min-h-[600px]">
                            <h2 className="text-lg font-semibold mb-6 flex items-center justify-between border-b border-gray-700 pb-4">
                                <div className="flex items-center gap-2">
                                    <span className={`w-3 h-3 rounded-full ${clothingType === 'shirt' ? 'bg-roblox-blue' : 'bg-roblox-green'}`}></span>
                                    {clothingType === 'shirt' ? 'Classic Shirt Template' : 'T-Shirt Graphic'}
                                </div>
                                {generatedImage && (
                                    <span className="text-xs font-normal text-green-400 flex items-center gap-1 animate-pulse">
                                        완료됨
                                    </span>
                                )}
                            </h2>

                            <div className="flex-1 flex flex-col items-center justify-center p-4">
                                {clothingType === 'shirt' ? (
                                    /* Classic Shirt Mode: Use TemplateMapper */
                                    <TemplateMapper
                                        sourceImage={generatedImage}
                                        showGuides={showGuides}
                                        scale={scale}
                                        onTemplateUpdate={setTemplateDataUrl}
                                    />
                                ) : (
                                    /* T-Shirt Mode: Show Generated Image Directly */
                                    <div className="flex flex-col items-center gap-6 w-full max-w-md">
                                        {generatedImage ? (
                                            <div className="relative group">
                                                <div className="absolute -inset-1 bg-gradient-to-r from-roblox-green to-teal-600 rounded-lg blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
                                                <img
                                                    src={generatedImage.src}
                                                    alt="Generated T-Shirt"
                                                    className="relative rounded-lg shadow-2xl border-2 border-gray-600 bg-checkerboard w-full aspect-square object-contain"
                                                />
                                                <div className="absolute top-2 right-2 bg-black/70 text-white text-xs px-2 py-1 rounded">512 x 512 (Recommended)</div>
                                            </div>
                                        ) : (
                                            <div className="w-full aspect-square bg-gray-900/50 rounded-lg border-2 border-dashed border-gray-700 flex flex-col items-center justify-center text-gray-500 p-8">
                                                <div className="w-16 h-16 mb-4 rounded-full bg-gray-800 flex items-center justify-center">
                                                    <svg className="w-8 h-8 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                                    </svg>
                                                </div>
                                                <span className="text-center">왼쪽 패널에서 생성 버튼을 누르면<br />여기에 결과가 표시됩니다.</span>
                                            </div>
                                        )}

                                        {generatedImage && (
                                            <button
                                                onClick={() => handleDownloadImage(generatedImage.src, 'roblox_tshirt.png')}
                                                className="px-8 py-3 rounded-full font-bold text-lg bg-gradient-to-r from-roblox-green to-emerald-600 text-white shadow-[0_0_20px_rgba(0,176,111,0.5)] hover:scale-105 active:scale-95 transition-all flex items-center gap-2"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                                                </svg>
                                                T-Shirt 다운로드
                                            </button>
                                        )}
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                </div>
            </main>
        </div>
    );
};

export default App;